config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    before_action :find_item, only: [:show, :edit, :update, :destroy]
    def index 
        @items = Item.all.order("created_at DESC")
    end

    def show
      
    end
    
    def new 
      @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to root_path 
        else 
            render 'new'
        end
    end

    def edit 
    end

    def update
        if @item.update(item_params)
            redirect_to item_path(@item)
        else
            render 'edit'
        end
    end

    def destroy
      @item.destroy
      redirect_to root_path
    end

    private

    def item_params
      params.require(:item).permit(:title, :description)
    end

    def find_item
        @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Item Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>
  <% end %>

app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit ToDo Item</h1>

  <%= render 'form' %>
</div>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <h2><%= link_to item.title, item %></h2>
  <p><%= item.description %></p>
<% end %>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New ToDo Item</h1>

  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <h2><%= @item.title %></h2>
  <p><%= @item.description %></p>

<div class="col-md-4 col-md-offset-4">
  <%= link_to "Back", root_path %>
  <%= link_to "Edit", edit_item_path(@item) %>
  <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are You Sure?" } %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiptime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
        <%= link_to "HipTime", root_path, class:"navbar-brand"%>
        </div>
          <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
          </ul>
          <% if user_signed_in? %>
          <%= link_to "Create Item", new_item_path, class: "navbar-text navbar-link"%>
          <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>